---
title: "Hurricane Intensification"
author: "James B. Elsner"
date: October 13, 2018
output: 
  html_document:
    keep_md: true
editor_options: 
  chunk_output_type: console
---

Import the data. The data are interpolated to one hour intervals. See Dropbox/Hurricanes/BestTrack.
```{r}
df <- read.csv(file = "best.interp.2016.csv", header = TRUE)
```

The `WmaxS` has units of knots to be consistent with the best-track wind speeds and the intensification rate (`DWmaxDt`) has units of knots per hour.
```{r}
library(dplyr)
begin <- 1986
end <- 2016
Tracks.df <- df %>%
  mutate(Int = WmaxS * .5144, 
         DIntDt = DWmaxDt * .5144) %>%
  filter(Yr >= begin, Yr <= end, Int >= 33, M == FALSE)
```

Distribution of hourly intensification rates.
```{r}
library(ggplot2)
library(scales)
ggplot(Tracks.df, aes(x = DIntDt)) +
  geom_freqpoly(bins = 50, size = 2) +
  geom_vline(xintercept = .643, color = "blue", size = 1.5) +
  geom_vline(xintercept = 0, color = "gray", size = .5) +
  xlab(expression(paste("Intensity Change [m ", s^-1, " per h]"))) +
  ylab("Number of Hours") +
  theme_minimal() +
  labs(title = "Hourly hurricane intensification/decay rates (1986-2016)", subtitle = "Steady state is most common. Blue line: average intensification rate needed to achieve rapid intensification.")
```

```{r}
length(Tracks.df$DIntDt)
length(unique(Tracks.df$Sid))
mean(Tracks.df$DIntDt)
fivenum(Tracks.df$DIntDt)
library(moments)
kurtosis(Tracks.df$DIntDt)
```
